// <auto-generated> from .build/design/strings.json via .build/gen_i18n.py </auto-generated>
namespace SimBoard.App.Localization;

/// <summary>Compile-checked names for every UI string.</summary>
public static class Keys
{
    /// <summary>555-astable-reg.sbp — แผ่นที่ 1</summary>
    public const string WinTitle = "winTitle";
    /// <summary>เริ่มโปรแกรม</summary>
    public const string NvStart = "nvStart";
    /// <summary>ออกแบบวงจร</summary>
    public const string NvSchem = "nvSchem";
    /// <summary>คลังอุปกรณ์</summary>
    public const string NvLib = "nvLib";
    /// <summary>บอร์ดทดลอง</summary>
    public const string NvBread = "nvBread";
    /// <summary>รันซิม</summary>
    public const string NvSim = "nvSim";
    /// <summary>เครื่องมือวัด</summary>
    public const string NvInst = "nvInst";
    /// <summary>นำเข้าลายวงจร</summary>
    public const string NvImport = "nvImport";
    /// <summary>ลายปริ๊น + AI</summary>
    public const string NvPcb = "nvPcb";
    /// <summary>เลเยอร์</summary>
    public const string NvLayers = "nvLayers";
    /// <summary>ตั้งค่า</summary>
    public const string NvSet = "nvSet";
    /// <summary>ไฟล์</summary>
    public const string MFile = "mFile";
    /// <summary>แก้ไข</summary>
    public const string MEdit = "mEdit";
    /// <summary>มุมมอง</summary>
    public const string MView = "mView";
    /// <summary>วางอุปกรณ์</summary>
    public const string MPlace = "mPlace";
    /// <summary>ซิมูเลต</summary>
    public const string MSim = "mSim";
    /// <summary>เครื่องมือ</summary>
    public const string MTools = "mTools";
    /// <summary>บอร์ด</summary>
    public const string MBoard = "mBoard";
    /// <summary>หน้าต่าง</summary>
    public const string MWin = "mWin";
    /// <summary>ช่วยเหลือ</summary>
    public const string MHelp = "mHelp";
    /// <summary>กริด</summary>
    public const string TbGrid = "tbGrid";
    /// <summary>ย่อ/ขยาย</summary>
    public const string TbZoom = "tbZoom";
    /// <summary>เล่น</summary>
    public const string BRun = "bRun";
    /// <summary>พัก</summary>
    public const string BPause = "bPause";
    /// <summary>หยุด</summary>
    public const string BStop = "bStop";
    /// <summary>ทีละสเต็ป</summary>
    public const string BStep = "bStep";
    /// <summary>สร้างใหม่</summary>
    public const string BNew = "bNew";
    /// <summary>เปิด...</summary>
    public const string BOpen = "bOpen";
    /// <summary>นำเข้า...</summary>
    public const string BImport = "bImport";
    /// <summary>ตกลง</summary>
    public const string BOk = "bOk";
    /// <summary>ยกเลิก</summary>
    public const string BCancel = "bCancel";
    /// <summary>นำไปใช้</summary>
    public const string BApply = "bApply";
    /// <summary>เลือกไฟล์...</summary>
    public const string BBrowse = "bBrowse";
    /// <summary>จับสัญญาณ</summary>
    public const string BProbe = "bProbe";
    /// <summary>ส่งเข้าสโคป</summary>
    public const string BScope = "bScope";
    /// <summary>คลังอุปกรณ์ · COMPONENT LIBRARY</summary>
    public const string PnLib = "pnLib";
    /// <summary>เลเยอร์ · LAYERS</summary>
    public const string PnLayers = "pnLayers";
    /// <summary>คุณสมบัติ · PROPERTIES</summary>
    public const string PnProps = "pnProps";
    /// <summary>ผลซิมูเลชันของ R2</summary>
    public const string PnSim = "pnSim";
    /// <summary>ค้นหาอุปกรณ์ / เบอร์ไอซี</summary>
    public const string LibSearch = "libSearch";
    /// <summary>PASSIVE › ตัวต้านทาน & ตัวเก็บประจุ</summary>
    public const string LibSub = "libSub";
    /// <summary>วางลงวงจร</summary>
    public const string LibPlace = "libPlace";
    /// <summary>ที่ใช้บ่อย</summary>
    public const string LibFav = "libFav";
    /// <summary>ค้นหา</summary>
    public const string LibSearchBtn = "libSearchBtn";
    /// <summary>เรียงตาม</summary>
    public const string LibSort = "libSort";
    /// <summary>ใช้บ่อยที่สุด</summary>
    public const string LibSortVal = "libSortVal";
    /// <summary>ดาต้าชีต · DATASHEET</summary>
    public const string LibDatasheet = "libDatasheet";
    /// <summary>เปิด PDF</summary>
    public const string LibPdf = "libPdf";
    /// <summary>ยินดีต้อนรับ</summary>
    public const string STitle = "sTitle";
    /// <summary>โปรแกรมทดลองวงจรอิเล็กทรอนิกส์ระดับมืออาชีพ — ออกแบบ วางบนบอร์ดทดลอง จำลองการทำงานด้วยเครื่องมือวัดจริง และทำลายปริ๊นต่อได้ในไฟล์เดียว</summary>
    public const string SSub = "sSub";
    /// <summary>ลิขสิทธิ์ใช้งานเชิงพาณิชย์ · 1 เครื่อง</summary>
    public const string SVer = "sVer";
    /// <summary>โปรเจกต์ล่าสุด</summary>
    public const string SRecent = "sRecent";
    /// <summary>เทมเพลตวงจร</summary>
    public const string STemplates = "sTemplates";
    /// <summary>ชื่อไฟล์</summary>
    public const string SColName = "sColName";
    /// <summary>ชนิด</summary>
    public const string SColKind = "sColKind";
    /// <summary>แก้ไขเมื่อ</summary>
    public const string SColDate = "sColDate";
    /// <summary>แสดงหน้านี้เมื่อเปิดโปรแกรม</summary>
    public const string SShowStart = "sShowStart";
    /// <summary>ผังวงจร</summary>
    public const string TbSchem = "tbSchem";
    /// <summary>บอร์ดทดลอง 2D</summary>
    public const string TbBread = "tbBread";
    /// <summary>ลายปริ๊น</summary>
    public const string TbPcb = "tbPcb";
    /// <summary>เนตลิสต์</summary>
    public const string TbSpice = "tbSpice";
    /// <summary>แผ่น 1 / 3 · A3</summary>
    public const string SheetOf = "sheetOf";
    /// <summary>ออสซิลโลสโคป</summary>
    public const string IScope = "iScope";
    /// <summary>มัลติมิเตอร์</summary>
    public const string IDmm = "iDmm";
    /// <summary>โลจิกอนาไลเซอร์</summary>
    public const string ILogic = "iLogic";
    /// <summary>ออโต้</summary>
    public const string IAuto = "iAuto";
    /// <summary>เคอร์เซอร์</summary>
    public const string ICursor = "iCursor";
    /// <summary>ช็อตเดียว</summary>
    public const string ISingle = "iSingle";
    /// <summary>ตารางจุดต่อและค่าที่วัดได้</summary>
    public const string BbLegend = "bbLegend";
    /// <summary>บอร์ดทดลองที่ติดตั้ง</summary>
    public const string BbBoards = "bbBoards";
    /// <summary>(กำลังใช้)</summary>
    public const string BbActive = "bbActive";
    /// <summary>วางอุปกรณ์อัตโนมัติด้วย AI</summary>
    public const string PcbAi = "pcbAi";
    /// <summary>AI อ่านผังวงจรแล้วจัดวางอุปกรณ์ เดินลายทองแดง และเว้นระยะความร้อน/แรงดันสูงให้อัตโนมัติ ก่อนส่งออกเป็นไฟล์ Gerber สำหรับสั่งทำแผ่นวงจร</summary>
    public const string PcbAiDesc = "pcbAiDesc";
    /// <summary>เป้าหมายการจัดวาง</summary>
    public const string PcbGoal = "pcbGoal";
    /// <summary>ความกว้างลาย</summary>
    public const string PcbTrace = "pcbTrace";
    /// <summary>เวีย (นอก/ใน)</summary>
    public const string PcbVia = "pcbVia";
    /// <summary>กำลังจัดวาง...</summary>
    public const string PcbPlacing = "pcbPlacing";
    /// <summary>จัดวาง + เดินลาย</summary>
    public const string PcbAuto = "pcbAuto";
    /// <summary>รายการตรวจ DRC</summary>
    public const string PcbCheck = "pcbCheck";
    /// <summary>ผล</summary>
    public const string PcbVal = "pcbVal";
    /// <summary>ส่งออก Gerber</summary>
    public const string PcbGerber = "pcbGerber";
    /// <summary>พิมพ์ลายปริ๊น 1:1</summary>
    public const string PcbPrint = "pcbPrint";
    /// <summary>นำเข้าลายวงจร / เนตลิสต์</summary>
    public const string ImTitle = "imTitle";
    /// <summary>ไฟล์</summary>
    public const string ImFile = "imFile";
    /// <summary>ไฟล์ในแพ็กเกจ</summary>
    public const string ImFiles = "imFiles";
    /// <summary>ไฟล์</summary>
    public const string ImColFile = "imColFile";
    /// <summary>เลเยอร์ปลายทาง</summary>
    public const string ImColLayer = "imColLayer";
    /// <summary>ขนาด</summary>
    public const string ImColSize = "imColSize";
    /// <summary>ตัวอย่าง</summary>
    public const string ImPreview = "imPreview";
    /// <summary>ตัวเลือกการนำเข้า</summary>
    public const string ImOpts = "imOpts";
    /// <summary>รูปแบบที่รองรับ</summary>
    public const string ImFormats = "imFormats";
    /// <summary>แปลงเป็นลายอัตโนมัติ</summary>
    public const string ImTrace = "imTrace";
    /// <summary>กำลังอ่าน</summary>
    public const string ImProgress = "imProgress";
    /// <summary>จัดการเลเยอร์</summary>
    public const string LmTitle = "lmTitle";
    /// <summary>ชื่อเลเยอร์</summary>
    public const string LmName = "lmName";
    /// <summary>ชิ้นงาน</summary>
    public const string LmObjects = "lmObjects";
    /// <summary>ความทึบ</summary>
    public const string LmOpacity = "lmOpacity";
    /// <summary>คุณสมบัติเลเยอร์</summary>
    public const string LmProps = "lmProps";
    /// <summary>สีเลเยอร์</summary>
    public const string LmColor = "lmColor";
    /// <summary>ดับเบิลคลิกชื่อเลเยอร์เพื่อเปลี่ยนชื่อ · Ctrl+คลิก เพื่อเลือกหลายเลเยอร์</summary>
    public const string LmHint = "lmHint";
    /// <summary>เพิ่มเติม...</summary>
    public const string LmMore = "lmMore";
    /// <summary>ตั้งค่าโปรแกรม</summary>
    public const string SetTitle = "setTitle";
    /// <summary>ทั่วไป</summary>
    public const string SetGen = "setGen";
    /// <summary>ภาษา</summary>
    public const string SetLang = "setLang";
    /// <summary>ธีมหน้าตา</summary>
    public const string SetThemeTab = "setThemeTab";
    /// <summary>ธีมหน้าต่างและปุ่ม</summary>
    public const string SetThemeQ = "setThemeQ";
    /// <summary>ธีมเปลี่ยนเฉพาะกรอบหน้าต่าง ปุ่ม และแผงควบคุม — พื้นที่ทำงานวงจรยังเป็นโทนมืดเสมอเพื่อให้เห็นลายวงจรและค่าที่วัดได้ชัด</summary>
    public const string SetThemeNote = "setThemeNote";
    /// <summary>ขนาดตัวอักษร</summary>
    public const string SetThemeFont = "setThemeFont";
    /// <summary>เปิดแอนิเมชันหน้าต่าง</summary>
    public const string SetThemeAnim = "setThemeAnim";
    /// <summary>เงาใต้เมนูและหน้าต่าง</summary>
    public const string SetThemeShadow = "setThemeShadow";
    /// <summary>ใช้ธีมนี้กับทุกหน้าต่างเครื่องมือวัด</summary>
    public const string SetThemeApplyAll = "setThemeApplyAll";
    /// <summary>ซิมูเลชัน</summary>
    public const string SetSimTab = "setSimTab";
    /// <summary>บอร์ด</summary>
    public const string SetBoard = "setBoard";
    /// <summary>คีย์ลัด</summary>
    public const string SetKeys = "setKeys";
    /// <summary>ภาษาที่ใช้แสดงผล</summary>
    public const string SetLangQ = "setLangQ";
    /// <summary>ตัวอย่างหน้าจอ</summary>
    public const string SetPreview = "setPreview";
    /// <summary>คุณสมบัติ — R2</summary>
    public const string SetPvTitle = "setPvTitle";
    /// <summary>ตัวต้านทาน 47 kΩ · ผิดพลาด ±1%</summary>
    public const string SetPvBody = "setPvBody";
    /// <summary>แรงดัน</summary>
    public const string SetPvV = "setPvV";
    /// <summary>กระแส</summary>
    public const string SetPvI = "setPvI";
    /// <summary>ความถี่</summary>
    public const string SetPvF = "setPvF";
    /// <summary>เปลี่ยนภาษาแล้วใช้งานได้ทันที ไม่ต้องปิดโปรแกรม · ชื่อเบอร์อุปกรณ์และหน่วยจะคงเป็นภาษาอังกฤษตามมาตรฐาน</summary>
    public const string SetNote = "setNote";
    /// <summary>ตัวต้านทาน · SMD 0805</summary>
    public const string PKindRes = "pKindRes";
    /// <summary>พร้อมใช้งาน</summary>
    public const string StIdle = "stIdle";
    /// <summary>กำลังจำลอง</summary>
    public const string StRun = "stRun";
}
